services:
  server:
    build: .
    environment:
      PORT: ${PORT:-42069}
    ports:
      - ${PORT:-42069}:${PORT:-42069}
    container_name: jellyping-server
    depends_on:
      - db
    volumes:
      - .env:/app/.env
    # restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-jellyping}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: jellyping-db

volumes:
  pgdata:
